# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_pathlen_cpp <- function(len, idx) {
    .Call(`_treestruct_calc_pathlen_cpp`, len, idx)
}

calc_sa_above_cpp <- function(sa, parentrow) {
    .Call(`_treestruct_calc_sa_above_cpp`, sa, parentrow)
}

