# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
assign_branchnum_cpp <- function(furcations, is_tip) {
    .Call(`_treestruct_assign_branchnum_cpp`, furcations, is_tip)
}

calc_pathlen_cpp <- function(len, parent_idx) {
    .Call(`_treestruct_calc_pathlen_cpp`, len, parent_idx)
}

calc_sa_above_cpp <- function(sa, parentrow) {
    .Call(`_treestruct_calc_sa_above_cpp`, sa, parentrow)
}

calc_total_x_above_internode_cpp <- function(x, parentrow) {
    .Call(`_treestruct_calc_total_x_above_internode_cpp`, x, parentrow)
}

get_children <- function(thisrow, parentrow) {
    .Call(`_treestruct_get_children`, thisrow, parentrow)
}

